### ISSUE TITLE
"KnifeDMGEnable": true,

### ISSUE THREAD

**Issue by y3request** [DeadSwimek/cs2-vip#11]
I have knife dmg enabled true and still no one can seem to knife me.
every other part of the plugin is working flawlessly.
![Screenshot 2023-12-01 234130](https://github.com/DeadSwimek/cs2-vip/assets/66896566/208ce818-1924-4094-a97c-9b166ba4f0b4)

The only thing I changed was I updated my Counter-strike sharp version and CS2 updated today or yesterday.

**Comment by y3request** [comment]
I updated cssharp 1 more time another update came out today.

Now your plugin is working exactly like it should be.

Not sure what happened. never gave me an error.

**Comment by DeadSwimek** [comment]
U must set KnifeDMGEnbale to False if you wanna giving DMG to VIP player by knife
