### ISSUE TITLE
Bug on map change

### ISSUE THREAD

**Issue by y3request** [DeadSwimek/cs2-vip#12]
I really like your plugin, but sometimes when I start server i join it says im vip, but cannot double jump
I switch the map, I can double jump.

then sometimes, i can double jump, i switch map, then i can't until i load map again.

I just finished scanning my log-all in cssharp logs. I cannot find any error for your plugin. So I don't know why it does this.

**Comment by DeadSwimek** [comment]
Type /vip for reload VIP permissions
