### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by paiuvlad** [DeadSwimek/cs2-vip#3]
Hello, I have few suggestions:
- packages to be configurable from json
- colored smokes & random
- health & armor to be configurable
- kill rewards(health,money,bullets filler)
- bunnyhops(if possible)
- to be able to create more vip groups

**Comment by DeadSwimek** [comment]
Bunnyhop is now possible, but i added doubble jump.
Colored smokes are added at 1.0.3
Health & armor to be configurable at version 1.1.0
kill rewards are added at 1.0.3
And packages, can't be in json, have too much functions to be added to json, if you wanna add some or edit you must compile by your own.
