### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by chycken** [DeadSwimek/cs2-vip#5]
Hi, do you provide an option to turn off chat messages (I mean+xp-s messages, because I use k4 system and it does that too, thats why it is unneccessary to me)....

**Comment by DeadSwimek** [comment]
Hi, 
this are in plugin from start, disable the bool EnableVIPPrefix.
Go to config file in CSS, Plugins folder and VIP.
Opne Config file find `EnableVIPPrefix` and rewrite to false.

**Comment by chycken** [comment]
> Hi, this are in plugin from start, disable the bool EnableVIPPrefix. Go to config file in CSS, Plugins folder and VIP. Opne Config file find `EnableVIPPrefix` and rewrite to false.

I set it to false, but still working it
