### ISSUE TITLE
Plugins overwriting chats color

### ISSUE THREAD

**Issue by Tian7777** [DeadSwimek/cs2-vip#7]
![image](https://github.com/DeadSwimek/cs2-vip/assets/41808115/a629ace9-21d2-4f0d-8027-7017fb459e06)
The blank one is what it suppose to be with cs2-tags plugin but it seems like vip plugin is overwriting all chat colors including K4-system and cs2-tags thus the color of other plugins not showing.
Tested without VIP status and it happens with everyone else as well.

**Comment by DeadSwimek** [comment]
Fixed in new releases (1.1.3), this release going out maybe at 11:00 CentralEU time.
